// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0o2XYysn9c7SowXsKwf4ELaTFjRKJkA0',
    appId: '1:250540036317:web:071e7715eabfd76f01cb34',
    messagingSenderId: '250540036317',
    projectId: 'debo-e6aa7',
    authDomain: 'debo-e6aa7.firebaseapp.com',
    storageBucket: 'debo-e6aa7.firebasestorage.app',
    measurementId: 'G-9XJZSV9WCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfzAMR7FeWR5S5oEc4by0-xmULSZJxmRc',
    appId: '1:250540036317:android:ccb7dfaff460c8b401cb34',
    messagingSenderId: '250540036317',
    projectId: 'debo-e6aa7',
    storageBucket: 'debo-e6aa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbM2jDxuawmvlPxrXmohf3nDRc0BSPQfw',
    appId: '1:250540036317:ios:59f78eb90e5f973601cb34',
    messagingSenderId: '250540036317',
    projectId: 'debo-e6aa7',
    storageBucket: 'debo-e6aa7.firebasestorage.app',
    iosBundleId: 'com.example.yourappname',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbM2jDxuawmvlPxrXmohf3nDRc0BSPQfw',
    appId: '1:250540036317:ios:59f78eb90e5f973601cb34',
    messagingSenderId: '250540036317',
    projectId: 'debo-e6aa7',
    storageBucket: 'debo-e6aa7.firebasestorage.app',
    iosBundleId: 'com.example.yourappname',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0o2XYysn9c7SowXsKwf4ELaTFjRKJkA0',
    appId: '1:250540036317:web:ebaca802f9842e9c01cb34',
    messagingSenderId: '250540036317',
    projectId: 'debo-e6aa7',
    authDomain: 'debo-e6aa7.firebaseapp.com',
    storageBucket: 'debo-e6aa7.firebasestorage.app',
    measurementId: 'G-6CPC53NEXL',
  );

}